name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'}}
    runs-on: self-hosted

    steps:
      - name: Environment Variable
        uses: |
          URL=${{ secrets.URL }}
          USERNAME=${{ secrets.USERNAME }}
          PASSWORD=${{ secrets.PASSWORD }}
          TOKEN=${{ secrets.TOKEN }}
          GLOBAL=${{ vars.GLOBAL }}

      - name: Deploy
        uses: |
          cd
          cd ~/AniSocial
          git pull
          ./gradlew clean
          ./gradlew shadowJar
          java -jar build/libs/AniSocial-1.0-SNAPSHOT-all.jar