name: Deploy

on:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'Java CI with Gradle' }}
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          cd
          cd ~/AniSocial
          git pull
          ./gradlew clean
          ./gradlew shadowJar
          sudo systemctl restart anisocial
        env:
          URL: ${{ secrets.URL }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TOKEN: ${{ secrets.TOKEN }}
          GLOBAL: ${{ vars.GLOBAL }}