name: Deploy

on:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'Java CI with Gradle' }}
    runs-on: self-hosted

    steps:
      - name: Environment Variable
        uses: |
          export URL=${{ secrets.URL }}
          export USERNAME=${{ secrets.USERNAME }}
          export PASSWORD=${{ secrets.PASSWORD }}
          export TOKEN=${{ secrets.TOKEN }}
          export GLOBAL=${{ vars.GLOBAL }}

      - name: Deploy
        uses: |
          cd
          cd ~/AniSocial
          git pull
          ./gradlew clean
          ./gradlew shadowJar
          java -jar build/libs/AniSocial-1.0-SNAPSHOT-all.jar